const assert=require('node:assert/strict');
require('../static/observatory-search.js');
const {parse,matches}=globalThis.ObservatorySearch;
const match=(q,labels)=>matches(parse(q),labels);
assert(match('AI 반도체',['AI 인프라','반도체']));
assert(match('AI AND 반도체',['AI 인프라','반도체']));
assert(!match('AI 반도체',['AI 인프라']));
assert(match('로봇 OR 반도체',['반도체']));
assert(match('로봇 | 반도체',['로봇']));
assert(match('"수출 통제"',['AI 수출 통제']));
assert(!match('"수출 통제"',['수출','통제']));
assert(match('AI -중국',['AI 안전']));
assert(!match('AI -중국',['AI 안전','중국']));
assert(match('AI 반도체 OR 로봇 -중국',['로봇']));
assert(!match('AI 반도체 OR 로봇 -중국',['로봇','중국']));
assert(match('ＡＩ',['ai']));
assert(match('"OR"',['OR']));
for(const q of ['AI OR','OR AI','"닫히지않음','-','AI AND OR 반도체'])assert(parse(q).error,q);
assert(!match('AI OR',['AI']));
assert(match('',['anything']));
console.log('Compound search: AND, OR, phrases, exclusions, precedence, malformed input passed');
